#!/bin/bash

UTILS="src/utils/cs164"
SUBSEC="$1"

echo -e "<div id=\"sidebar\">"
echo -e "\t<div class=\"content\">"

CURRSEC="0"

tail -n +2 src/cs164/sections.tsv | while IFS=$'\t' read -r NUMBER TITLE DIRECTORY FILE UPDATED
do
	if [[ "${NUMBER}" =~ ^0.* ]]
	then
		echo -e "\t</div>"
		echo -e "\t<hr>"
		echo -e "\t<div class=\"content\">"

		LINK="${DIRECTORY}/${FILE}.html"

		[[ "${DIRECTORY}" == "LINK" ]] && LINK="${FILE}"
		[[ -z "${FILE}" ]] && LINK="${DIRECTORY}.html"

		echo -e "\t\t<a href=\"${LINK}\"><b>${TITLE}</b></a>"

		while IFS=$'\t' read -r SECTION TAB ID
		do
			[[ -z "${ID}" ]] && ID="$("${UTILS}/make_id" "${TAB}" )"
			echo -e "\t\t<a href=\"${LINK}#${ID}\">&nbsp;<b>&#8227;</b>&nbsp;${TAB}</a>"
		done < <(grep "${NUMBER}" "src/cs164/subsections.tsv")

		continue
	fi


	LINK="${DIRECTORY}/${FILE}.html"

	if [[ "${CURRSEC}" != "${NUMBER%%.*}" ]]
	then
		CURRSEC="${NUMBER%%.*}"
		echo -e "\t</div>"
		echo -e "\t<hr>"
		echo -e "\t<div class=\"content\">"
		NUMBER="Chapter ${NUMBER}"
		LINK="${DIRECTORY}/"
	fi
	echo -e "\t\t<a href=\"${LINK}\"><b>${NUMBER} :</b> ${TITLE}</a>"

	if [[ "${NUMBER}" == "${SUBSEC}" ]]
	then
		while IFS=$'\t' read -r SECTION TAB ID
		do
			[[ -z "${ID}" ]] && ID="$("${UTILS}/make_id" "${TAB}" )"
			echo -e "\t\t<a href=\"${LINK}#${ID}\">&nbsp;<b>&#8227;</b>&nbsp;${TAB}</a>"
		done < <(grep "${SUBSEC}" "src/cs164/subsections.tsv")
	fi
done

echo -e "\t</div>"
echo -e "</div>"
