#!/bin/bash
# Charlie Rose
# A script to build my webpages for my personal site

MD_SRC="./src/"
IN_FILE="$1"
TEMPLATE="$2"

OUT_FILE=${IN_FILE#${MD_SRC}}
OUT_FILE=${OUT_FILE%.md}.html

CONTENT="$("src/utils/mdtohtml.awk" "${IN_FILE}")"

HTMLPAGE=${TEMPLATE}
HTMLPAGE="${HTMLPAGE/<!-- HEADING -->/ }"
HTMLPAGE="${HTMLPAGE/<!-- CONTENT -->/${CONTENT}}"

echo -e "${HTMLPAGE}" > "${OUT_FILE}"
