#!/bin/bash
# Charlie Rose
# A script to build my webpages for my personal site

LASTBUILD="./utils/lastbuild.txt"
BUILDFILES="./utils/build ./utils/template.html ./utils/mdtohtml"
BUILDCHNG=""

TEMPLATE=$(cat ./utils/template.html)
MD_SRC='./markdownfiles'
BLOGMD_SRC="${MD_SRC}/blog"
BLOGPOST_SRC="./blogposts"
BLOG_TEMPLATE="${TEMPLATE}"
BLOG_TEMPLATE=${BLOG_TEMPLATE//.\//..\/..\/}

CARRAY=( "pp" "pb" "pg" "py" "po" "pr" "pi" )
CHL=${#CARRAY[@]}

echo "Last Build: $(cat $LASTBUILD)"

# See if the build change was intentional
for f in $BUILDFILES
do
	if [ "$f" -nt "$LASTBUILD" ]
	then
		echo -e "\033[01;33mWARNING\033[00m: $f has been changed since last build"
		echo "Continue? [y/n]"
		read CONT

		if [ "$CONT" != "y" ]
		then
			echo "Aborted"
			exit 1
		fi

		BUILDCHNG="true"
	else
		echo "$f has not been changed since last build"
	fi
done

for IN_FILE in "${MD_SRC}"/*.md
do
	OUT_FILE=.${IN_FILE#${MD_SRC}}
	OUT_FILE=${OUT_FILE%.md}.html

	# Don't build the file if
	#	The markdown is older than the HTML file
	#	AND the build script hasn't been changed
	#	AND the template hasn't been changed
	if [ "${IN_FILE}" -ot "${OUT_FILE}" ] && [ -z $BUILDCHNG ] && [ -z $TMPLTCHNG ]
	then
		echo "Ignored ${IN_FILE}": No recent changes
		continue
	fi

	echo "Building ${OUT_FILE} from ${IN_FILE}..."
	utils/build_page "${IN_FILE}" "${TEMPLATE}"
done

echo "Completed main HTML files from Markdown"

utils/build_teaching

utils/build_research

utils/build_projects

utils/build_activism

utils/build_blog

CONTENT=$(tail -n +2 "${MD_SRC}/index.md")
CONTENT="${CONTENT%%###*}"
CONTENT="${CONTENT//|/'\n'}"
echo -e "${CONTENT}<https://charlierose.dev>" > README.md

echo "Built README.md"

for FILE in ./*.html
do
	utils/check_links ${FILE}
done

LB=$(date)
echo "Built $LB" > "$LASTBUILD"
echo "Built $LB"

