#!/bin/bash
# Charlie Rose
# Building the Blog for my site

MD_SRC='./markdownfiles'
BLOGMD_SRC="${MD_SRC}/blog"
BLOGDIR="./blogposts"
POSTLIST="./utils/blogposts.tsv"
TEMPLATE=$(cat ./utils/template.html)
BLOG_TEMPLATE="${TEMPLATE}"
BLOG_TEMPLATE=${BLOG_TEMPLATE//.\//..\/..\/}
BLOG_TEMPLATE="${BLOG_TEMPLATE/<!-- HEADING -->/ - Blog}"

if [ ! -e "${BLOGDIR}" ]
then
	mkdir ${BLOGDIR}
	echo "Built blogpost directory"
fi


# Build individual blog files first

echo "Building blog HTML files from Markdown"

while IFS= read -r LINE
do
	DATE="$(echo "${LINE}" | cut -f 1)"
	NAME="$(echo "${LINE}" | cut -f 2)"
	TAGS="$(echo "${LINE}" | cut -f 3)"
	CSSS="$(echo "${LINE}" | cut -f 4)"
	NAVI="$(echo "${LINE}" | cut -f 5)"

	if [[ -n "${NAVI}" ]]; then continue; fi

	DIRDATE="${DATE//-/}"

	IN_FILE="${BLOGMD_SRC}/${NAME}.md"
	OUT_FILE="${BLOGDIR}/${DIRDATE}/${NAME}.html"

	if [[ ! -e "${IN_FILE}" ]]
	then
		echo -e "Error: File '${IN_FILE}' does not exist"
		continue
	fi

	if [ ! -e "${BLOGDIR}/${DIRDATE}" ]
	then
		mkdir "${BLOGDIR}/${DIRDATE}"
		echo "Made ${BLOGDIR}/${DIRDATE} directory for blogposts"
	fi

	CSSPAGES=""
	for THISCSS in $CSSS
	do
		CSSPAGES="${CSSPAGES}<link rel=\"stylesheet\" type=\"text/css\" href=\"${THISCSS}\">\n"
	done


	CONTENT="$(pandoc -p "${IN_FILE}")"
	echo " Coverted to HTML with pandoc"
	CONTENT="$(./utils/mdtohtml "${CONTENT}")"
	echo " Adding Charlie customization"
	CONTENT="${CONTENT}\n\n<hr>\n\n<a href=\"#top\">Back to Top</a>\n"

	# Fixing template links and inserting content
	HTMLPAGE="${BLOG_TEMPLATE}"
	HTMLPAGE="${HTMLPAGE/<!-- XTRACSS -->/${CSSPAGES}}"
	HTMLPAGE="${HTMLPAGE/<!-- CONTENT -->/${CONTENT}}"

	
	# Build HTML page
	echo -e "${HTMLPAGE}" > "${OUT_FILE}"
	
	utils/check_links "${OUT_FILE}"

	echo "  Built ${OUT_FILE} from ${IN_FILE}"

done < <(tail -n +2 "${POSTLIST}")

echo "Built all blog HTML files from Markdown"


## Build Blog Navigation separately

NAV_CONTENT=" "
CURRYEAR=""

while IFS= read -r LINE
do
	DATE="$(echo "${LINE}" | cut -f 1)"
	NAME="$(echo "${LINE}" | cut -f 2)"
	TAGS="$(echo "${LINE}" | cut -f 3)"
	CSSS="$(echo "${LINE}" | cut -f 4)"
	NAVI="$(echo "${LINE}" | cut -f 5)"

	if [[ -n "${NAVI}" ]]; then continue; fi

	IN_FILE="${BLOGMD_SRC}/${NAME}.md"
	if [[ ! -e "${IN_FILE}" ]]; then continue; fi

	TITLE="$(head -n 1 ${IN_FILE})"
	TITLE="${TITLE#"# "}"
	TITLE="${TITLE//\\/}"

	YEAR="${DATE::4}"
	MONTH="${DATE:5:2}"
	DAY="${DATE:8:2}"
	PRETTYDATE="${MONTH}/${DAY}/${YEAR}"
	DIRDATE="${DATE//-/}"

	if [[ "${YEAR}" != "${CURRYEAR}" ]]
	then
		NAV_CONTENT="${NAV_CONTENT}\t<h3 class='blogh'>${DATE%%-*}</h3>\n"
		CURRYEAR="${YEAR}"
	fi

	BLOGLINK="${BLOGDIR#./}/${DIRDATE}/${NAME}.html"

	ENTRY_LINK="\t<a class='bloglink' href='${BLOGLINK}'>${PRETTYDATE} : ${TITLE}</a>"
	NAV_CONTENT="${NAV_CONTENT}${ENTRY_LINK}<br>\n"

done < <(tail -n +2 "${POSTLIST}")

OUT_FILE="blog.html"

HTMLPAGE="${TEMPLATE}"
HTMLPAGE="${HTMLPAGE/<!-- CONTENT -->/${NAV_CONTENT}}"

echo -e "${HTMLPAGE}" > "${OUT_FILE}"

echo "Built main blog page"



